### PR TITLE
ENH: add more indexing and read mapping options

### PR DESCRIPTION
**Pull request by misialq**
WIP

Depends on https://github.com/qiime2/q2-types/pull/325.

### CODE REVIEW

**Review by Sann5 — COMMENTED** [review]
Hey Michal! Would you like me to test this on some data you have? All the tests pass locally.

**Comment by misialq** [comment]
Hey @Sann5, I'd like you to test it on some data they maybe _you_ have - I already tested it on mine. You must have something in your tutorial? At least for mapping reads to contigs and MAGs. (do you also have dereplication step in the tutorial? if yes, you should be able to test everything)

**Comment by Sann5** [comment]
Hey @misialq,

So I tried it on some data I had lying around as you suggested. Everything ran without errors 🚀. This is what I tried:

1. `index-mags` ✅ 
2. `index-derep-mags` ✅ 
3. `index-contigs` ✅ 
4. `map-reads` with the indexes from 1) and 3). ✅ 

I didn't have reads for 2). I could take the mags for which I have read, dereplicate them, index them, and then try `map-reads` but I don't know where to get the distance matrix from in `dereplicate-mags`.

**Comment by misialq** [comment]
Hey @Sann5, thanks for running all the tests! 🙇 You don't need to run anything else for case 2 - this is the only one that I tested extensively myself (as I'm using it in my analysis pipeline) 😅 Are you still in the process of reviewing the code or are you done?

**Comment by Sann5** [comment]
@misialq let me shortly take another look. A lot of the code I only skimmed over because I was confused about what the changes were. But now that I have used it I think I can review it better :)

**Review by Sann5 — APPROVED** [review]
Looks good to me @misialq 🚀

**Pull request merged**
