### PR TITLE
No more types genomics

### PR DESCRIPTION
**Pull request by Oddant1**
Change types_genomics to types in accordance with qiime2/q2-types#309

Blocked by qiime2/q2-types#309

### CODE REVIEW

**Review by lizgehret — APPROVED** [review]
this all looks reasonable - pending local testing, i'll merge the blocking PR in types and then we can re-run CI to make sure everything passes.

**Comment by lizgehret** [comment]
ah, i figured out why this (and the PR in moshpit) are still failing. i ran a Prepare using amplicon (thinking that would be an easier rebuild than another shotgun, due to the distro size) - but these plugins will only look under the shotgun channel for newly built packages, so the changes from q2-types aren't being pulled in. I'm going to run a new Prepare for shotgun to get this sorted and _then_ re-running these should be successful.

**Comment by lizgehret** [comment]
Okay so unfortunately this is a bit of a chicken and egg situation - CI won't pass here until there's a working metapackage build, and the metapackage won't build until these changes take into effect (failed metapackage shown [here](https://github.com/qiime2/distributions/actions/runs/7910949310/job/21614211904?pr=144#step:8:1912)). These PRs need to get merged before an updated shotgun metapackage can be built successfully. @nbokulich is it possible to override the required statuses passing and get this PR (along with the [RESCRIPt](https://github.com/bokulich-lab/RESCRIPt/pull/176) and [moshpit](https://github.com/bokulich-lab/q2-moshpit/pull/133) PRs) merged?

**Comment by nbokulich** [comment]
Thanks for the notification @lizgehret ! Merging this to resolve the chicken-vs-egg problem

**Pull request merged**
