### PR TITLE
CI/DEP: update recipe and add quast

### PR DESCRIPTION
**Pull request by ebolyen**
Testing my theory in https://github.com/bokulich-lab/q2-assembly/issues/16#issuecomment-1156884212.

Also some super minor changes to the recipe to match our current build-process a bit better.

### CODE REVIEW

**Comment by ebolyen** [comment]
Ah, still no py38 builds for `quast`. I guess it's never that easy.

Strange that bioconda didn't just build those automatically though.

**Comment by ebolyen** [comment]
And this would be the reason:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/quast/meta.yaml#L10-L12

Looks like the recipe can probably be updated:
https://github.com/ablab/quast/commit/bc4af762a7f53176d66bd5e6c5b7d28376d28e11

A robot did the last update, so it wouldn't have known:
https://github.com/bioconda/bioconda-recipes/pull/35252

**Comment by ebolyen** [comment]
Hopefully there will be a 3.8 build soonish: https://github.com/bioconda/bioconda-recipes/pull/35385

**Comment by ebolyen** [comment]
Done!

**Review by misialq — APPROVED** [review]
Hey @ebolyen, this is great - thanks for investigating and for the changes!

**Comment by ebolyen** [comment]
Awesome, this should be ready for merge then.

**Pull request merged**
