### PR TITLE
REF: fix private imports for q2-types refactor

### PR DESCRIPTION
**Pull request by ebolyen**
Fixes some private imports and uses a utility to get the same effect.

Related to: https://github.com/qiime2/q2-types/pull/342

### CODE REVIEW

**Comment by ebolyen** [comment]
Full distro trial here: https://github.com/qiime2/distributions/actions/runs/10084580203?pr=314

**Review by lizgehret — APPROVED** [review]

**Comment by ebolyen** [comment]
Tests won't pass until this is merged. We'll need another override, sorry @misialq!

**Comment by lizgehret** [comment]
Psst, little bump @misialq 🤓 sorry to keep bothering you with these!

**Comment by misialq** [comment]
Again, sorry @lizgehret, @ebolyen: I have neglected GitHub recently _a bit_ - merging now! 🙇

**Pull request merged**
